# Generated by Django 3.2.13 on 2022-07-17 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155, verbose_name='Organisation Name')),
                ('logo', models.URLField(verbose_name='Oragnisation Logo URL')),
                ('email', models.EmailField(blank=True, max_length=155, unique=True, verbose_name='Organisation Email')),
                ('phone', models.CharField(blank=True, max_length=12, null=True, verbose_name='Organisation Phone Number')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Organisation Address')),
                ('description', models.CharField(max_length=500, verbose_name='Organisation Description')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin')),
            ],
            options={
                'verbose_name': 'org',
                'verbose_name_plural': 'orgs',
                'db_table': 'organisations',
            },
        ),
    ]
