# Generated by Django 3.2.12 on 2022-05-18 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RandomModel',
        ),
    ]
